[machines.arc_furnace]
	#A modifier to apply to the energy costs of every arc furnace recipe
	#Range: 0.001 ~ 1000.0
	energyModifier = 1.0
	#A modifier to apply to the time of every arc furnace recipe
	#Range: 0.001 ~ 1000.0
	timeModifier = 1.0