[spirit_job]
	#The multiplier to each crushing recipe's output count for Tier 1 (Foliot) Crusher Spirits.
	tier1CrusherOutputMultiplier = 1.0
	#The multiplier to each crushing recipe's output count for Tier 2 (Djinni) Crusher Spirits.
	tier2CrusherOutputMultiplier = 1.5
	#The multiplier to each crushing recipe's output count for Tier 3 (Afrit) Crusher Spirits.
	tier3CrusherOutputMultiplier = 2.0
	#The multiplier to each crushing recipe's output count for Tier 4 (Marid) Crusher Spirits.
	tier4CrusherOutputMultiplier = 3.0